
CREATE TABLE public.main_themes (
	id int4 NOT NULL,
	main_theme text NULL,
	CONSTRAINT main_themes_pkey PRIMARY KEY (id)
);

CREATE TABLE public.periods (
	id varchar(7) NOT NULL,
	dt_beg date NOT NULL,
	dt_end timestamp NOT NULL,
	CONSTRAINT periods_pkey PRIMARY KEY (id)
);

CREATE TABLE public.songs (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	num int4 NOT NULL,
	"name" text NOT NULL,
	alt_name text NULL,
	en_name text NULL,
	authors text NULL,
	"text" text NULL,
	theme text NULL,
	cnt_using int4 DEFAULT 0 NULL,
	chords_file_id text NULL,
	audio_file_id text NULL,
	youtube_url text NULL,
	CONSTRAINT songs_pkey PRIMARY KEY (num)
);

CREATE TABLE public.users (
	id serial4 NULL,
	telgrm_user_id int8 NOT NULL,
	f_name text NULL,
	l_name text NULL,
	username text NULL,
	lang text NULL,
	first_access date DEFAULT CURRENT_DATE NULL,
	last_access timestamp DEFAULT (CURRENT_TIMESTAMP(0) + '01:00:00'::interval) NULL,
	u_cnt_msg int4 DEFAULT 1 NULL,
	u_cnt_chords int4 DEFAULT 0 NULL,
	CONSTRAINT users_pkey PRIMARY KEY (telgrm_user_id)
);

CREATE TABLE public.metrics (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	cnt_by_content int4 DEFAULT 0 NULL,
	cnt_by_nums int4 DEFAULT 0 NULL,
	cnt_by_txt int4 DEFAULT 0 NULL,
	cnt_by_chords int4 DEFAULT 0 NULL,
	cnt_by_audio int4 DEFAULT 0 NULL,
	cnt_by_youtube int4 DEFAULT 0 NULL,
	cnt_by_users int4 DEFAULT 0 NULL,
	id_period varchar(7) NOT NULL,
	cnt_by_singers int4 DEFAULT 0 NULL,
	cnt_by_themes int4 DEFAULT 0 NULL,
	cnt_by_fvrt int4 DEFAULT 0 NULL,
	CONSTRAINT metrics_pkey PRIMARY KEY (id),
	CONSTRAINT metrics_id_periods_fkey FOREIGN KEY (id_period) REFERENCES public.periods(id)
);
CREATE INDEX fki_metrics_id_periods_fkey ON public.metrics USING btree (id_period);

CREATE TABLE public.themes (
	id int4 NOT NULL,
	theme text NULL,
	song_nums text NULL,
	main_theme text NULL,
	main_theme_id int4 NULL,
	CONSTRAINT themes_pkey PRIMARY KEY (id),
	CONSTRAINT fk_main_theme_id FOREIGN KEY (main_theme_id) REFERENCES public.main_themes(id)
);

CREATE TABLE public.user_song_link (
	tg_user_id int8 NOT NULL,
	song_num int4 NOT NULL,
	CONSTRAINT user_song_link_song_num_fkey FOREIGN KEY (song_num) REFERENCES public.songs(num),
	CONSTRAINT user_song_link_tg_user_id_fkey FOREIGN KEY (tg_user_id) REFERENCES public.users(telgrm_user_id)
);

CREATE TABLE public.theme_song_link (
	theme_id int4 NOT NULL,
	song_num int4 NOT NULL,
	CONSTRAINT theme_song_link_id_theme_fkey FOREIGN KEY (theme_id) REFERENCES public.themes(id),
	CONSTRAINT theme_song_link_song_num_fkey FOREIGN KEY (song_num) REFERENCES public.songs(num)
);